#!/bin/bash - пишу какой интерпретатор использовать
RESULT=$(ls /etc) - так обьявляется переменная (знак $ обязателен!)
if [[ $RESULT = *"apt"* & $? = 0 ]]; - условие if
then echo "SUCCESS" - вывод на экран SUCCESS
else echo "FAIL" - вывод на экран FAIL
fi - окночание if
